import type { ProjectCard } from "@/types";

export const MOCK_PROJECTS: ProjectCard[] = [
  {
    id: "1",
    title: "Aba-Ikot Ekpene Expressway Dualisation",
    slug: "aba-ikot-ekpene-highway",
    description:
      "Full reconstruction and dualisation of the 34km economic arterial highway connecting commercial hub Aba to Akwa Ibom state.",
    budget: 65_000_000_000,
    state: "Abia",
    lga: "Aba North",
    sector: "INFRASTRUCTURE",
    status: "ONGOING",
    progress: 68,
    imageUrl: "/projects/highway.png",
    ministry: "Federal Ministry of Works",
    startDate: "2023-10-15",
    contractor: "China Civil Engineering Construction",
    beneficiaries: 3_500_000,
  },
  {
    id: "2",
    title: "Modibbo Adama Medical Centre Expansion",
    slug: "modibbo-adama-medical-centre",
    description:
      "State-of-the-art expansion of teaching hospital facilities including emergency trauma centre, diagnostic labs, and pediatric wards.",
    budget: 42_000_000_000,
    state: "Adamawa",
    lga: "Yola North",
    sector: "HEALTHCARE",
    status: "ONGOING",
    progress: 55,
    imageUrl: "/projects/hospital.png",
    ministry: "Federal Ministry of Health",
    startDate: "2023-11-01",
    contractor: "Julius Berger Nigeria Plc",
    beneficiaries: 2_200_000,
  },
  {
    id: "3",
    title: "Ibom Deep Seaport Access Highway Corridor",
    slug: "ibom-deep-seaport-access-highway",
    description:
      "Dual-carriageway access corridor connecting maritime logistics networks to the Ibom Industrial City and Gulf of Guinea.",
    budget: 180_000_000_000,
    state: "Akwa Ibom",
    lga: "Ibeno",
    sector: "INFRASTRUCTURE",
    status: "ONGOING",
    progress: 72,
    imageUrl: "/projects/highway.png",
    ministry: "Federal Ministry of Works",
    startDate: "2024-01-10",
    contractor: "Hitech Construction Ltd",
    beneficiaries: 5_400_000,
  },
  {
    id: "4",
    title: "Second Niger Bridge Phase II Access Roads",
    slug: "second-niger-bridge-phase-ii",
    description:
      "Completion of Phase II connecting interchanges from Asaba through Onitsha to the Ihiala commercial corridor.",
    budget: 95_000_000_000,
    state: "Anambra",
    lga: "Onitsha South",
    sector: "TRANSPORTATION",
    status: "ONGOING",
    progress: 75,
    imageUrl: "/projects/highway.png",
    ministry: "Federal Ministry of Works",
    startDate: "2023-08-01",
    contractor: "Julius Berger Nigeria Plc",
    beneficiaries: 6_000_000,
  },
  {
    id: "5",
    title: "Northeast Regional Solar Substation Grid",
    slug: "northeast-regional-solar-grid",
    description:
      "150MW utility-scale solar photovoltaic plant with smart distribution grid integrating clean energy across Bauchi and neighbors.",
    budget: 78_000_000_000,
    state: "Bauchi",
    lga: "Ganjuwa",
    sector: "POWER",
    status: "ONGOING",
    progress: 52,
    imageUrl: "/projects/solar.png",
    ministry: "Federal Ministry of Power",
    startDate: "2024-02-15",
    contractor: "Sterling & Wilson Renewable Power",
    beneficiaries: 4_100_000,
  },
  {
    id: "6",
    title: "Nembe-Brass Coastal Road & Wetland Preservation",
    slug: "nembe-brass-coastal-road",
    description:
      "Strategic coastal road unlocking Brass Island crude terminal and logistics base, alongside marine wetland ecosystem protection.",
    budget: 110_000_000_000,
    state: "Bayelsa",
    lga: "Brass",
    sector: "ENVIRONMENT",
    status: "ONGOING",
    progress: 61,
    imageUrl: "/projects/highway.png",
    ministry: "Federal Ministry of Environment",
    startDate: "2023-09-20",
    contractor: "Setraco Nigeria Ltd",
    beneficiaries: 1_800_000,
  },
  {
    id: "7",
    title: "Makurdi Grain Storage Silos & Agro Logistics Hub",
    slug: "makurdi-grain-silos-hub",
    description:
      "100,000-tonne strategic grain reserves facility with automated drying and processing infrastructure to enhance national food security.",
    budget: 48_000_000_000,
    state: "Benue",
    lga: "Makurdi",
    sector: "AGRICULTURE",
    status: "ONGOING",
    progress: 58,
    imageUrl: "/projects/agriculture.png",
    ministry: "Federal Ministry of Agriculture",
    startDate: "2023-07-15",
    contractor: "Agro Allied Industries Ltd",
    beneficiaries: 3_200_000,
  },
  {
    id: "8",
    title: "Maiduguri Clean Water Initiative",
    slug: "maiduguri-clean-water-initiative",
    description:
      "Comprehensive municipal water treatment plant restoration, borehole networks, and distribution piping serving resilient communities.",
    budget: 120_000_000_000,
    state: "Borno",
    lga: "Maiduguri",
    sector: "WATER",
    status: "ONGOING",
    progress: 45,
    imageUrl: "/projects/water_dam.png",
    ministry: "Federal Ministry of Water Resources",
    startDate: "2023-11-01",
    contractor: "China Harbour Engineering",
    beneficiaries: 2_800_000,
  },
  {
    id: "9",
    title: "Calabar Deep Sea Port Access & Tourism Corridor",
    slug: "calabar-deep-sea-port-corridor",
    description:
      "Channel dredging and dualized coastal expressway boost connecting Calabar Seaport to the Tinapa Eco-Tourism Free Zone.",
    budget: 140_000_000_000,
    state: "Cross River",
    lga: "Calabar South",
    sector: "TRANSPORTATION",
    status: "ONGOING",
    progress: 63,
    imageUrl: "/projects/highway.png",
    ministry: "Federal Ministry of Transportation",
    startDate: "2024-03-01",
    contractor: "Dredging International NV",
    beneficiaries: 2_900_000,
  },
  {
    id: "10",
    title: "Warri-Itakpe Rail Commercial Extension",
    slug: "warri-itakpe-rail-extension",
    description:
      "Modernization and spur line extension connecting Warri Port to industrial gas processing plants in Kwale.",
    budget: 210_000_000_000,
    state: "Delta",
    lga: "Warri South",
    sector: "TRANSPORTATION",
    status: "ONGOING",
    progress: 70,
    imageUrl: "/projects/railway.png",
    ministry: "Federal Ministry of Transportation",
    startDate: "2023-05-10",
    contractor: "CCECC Nigeria Ltd",
    beneficiaries: 4_800_000,
  },
  {
    id: "11",
    title: "Abakaliki Rice Processing & Irrigation Scheme",
    slug: "abakaliki-rice-irrigation-scheme",
    description:
      "5,000-hectare automated rice irrigation dam and commercial milling hub boosting local production and export readiness.",
    budget: 38_000_000_000,
    state: "Ebonyi",
    lga: "Abakaliki",
    sector: "AGRICULTURE",
    status: "ONGOING",
    progress: 66,
    imageUrl: "/projects/agriculture.png",
    ministry: "Federal Ministry of Agriculture",
    startDate: "2023-08-20",
    contractor: "OLAM Rice Farm Partners",
    beneficiaries: 1_900_000,
  },
  {
    id: "12",
    title: "Benin Digital Innovation Park & Fiber Backbone",
    slug: "benin-digital-innovation-park",
    description:
      "3,000-seat technology incubator, software development park, and regional high-speed optic fiber transmission backbone.",
    budget: 55_000_000_000,
    state: "Edo",
    lga: "Oredo",
    sector: "TECHNOLOGY",
    status: "ONGOING",
    progress: 71,
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
    ministry: "Federal Ministry of Communications",
    startDate: "2023-09-01",
    contractor: "MainOne Cable Company",
    beneficiaries: 3_100_000,
  },
  {
    id: "13",
    title: "Ado-Ekiti Knowledge Zone Power Substation",
    slug: "ado-ekiti-knowledge-zone-power",
    description:
      "Dedicated 132/33kV power transmission substation guaranteeing 24/7 power to the Ekiti Special Agro-Industrial Processing Zone.",
    budget: 32_000_000_000,
    state: "Ekiti",
    lga: "Ado Ekiti",
    sector: "POWER",
    status: "ONGOING",
    progress: 69,
    imageUrl: "/projects/solar.png",
    ministry: "Federal Ministry of Power",
    startDate: "2024-01-15",
    contractor: "Transmission Company of Nigeria",
    beneficiaries: 1_600_000,
  },
  {
    id: "14",
    title: "Enugu Smart Education Hub & Digital Library",
    slug: "enugu-smart-education-hub",
    description:
      "Modern tertiary e-learning infrastructure, STEM labs, and teacher training complex serving southeastern academic institutions.",
    budget: 45_000_000_000,
    state: "Enugu",
    lga: "Enugu North",
    sector: "EDUCATION",
    status: "ONGOING",
    progress: 74,
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    ministry: "Federal Ministry of Education",
    startDate: "2023-07-01",
    contractor: "TetFund Construction Partners",
    beneficiaries: 2_400_000,
  },
  {
    id: "15",
    title: "National Digital Identity Programme",
    slug: "national-digital-identity-programme",
    description:
      "Nationwide rollout of digital identity infrastructure enabling seamless access to government services and financial inclusion.",
    budget: 450_000_000_000,
    state: "FCT",
    lga: "Abuja Municipal",
    sector: "TECHNOLOGY",
    status: "ONGOING",
    progress: 78,
    imageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80",
    ministry: "Federal Ministry of Communications",
    startDate: "2023-06-01",
    contractor: "NIMC Consortium",
    beneficiaries: 120_000_000,
  },
  {
    id: "16",
    title: "Dadin Kowa Multipurpose Hydro & Irrigation",
    slug: "dadin-kowa-hydro-irrigation",
    description:
      "40MW hydro-power plant expansion coupled with a 6,000-hectare gravity irrigation network for dry season farming.",
    budget: 85_000_000_000,
    state: "Gombe",
    lga: "Yamaltu/Deba",
    sector: "WATER",
    status: "ONGOING",
    progress: 54,
    imageUrl: "/projects/water_dam.png",
    ministry: "Federal Ministry of Water Resources",
    startDate: "2023-12-01",
    contractor: "Mabon Limited",
    beneficiaries: 2_100_000,
  },
  {
    id: "17",
    title: "Owerri-Port Harcourt Dual Expressway Rehabilitation",
    slug: "owerri-port-harcourt-highway",
    description:
      "Heavy-duty asphalt pavement reconstruction and flyover interchange installation linking Imo commercial trade to Rivers oil terminals.",
    budget: 72_000_000_000,
    state: "Imo",
    lga: "Owerri Municipal",
    sector: "INFRASTRUCTURE",
    status: "ONGOING",
    progress: 67,
    imageUrl: "/projects/highway.png",
    ministry: "Federal Ministry of Works",
    startDate: "2023-10-01",
    contractor: "Craneburg Construction",
    beneficiaries: 4_200_000,
  },
  {
    id: "18",
    title: "Dutse Solar Power Grid & Wheat Scheme",
    slug: "dutse-solar-wheat-scheme",
    description:
      "100MW off-grid solar installation powering 15,000 hectares of mechanized wheat farms along the Hadejia river valley.",
    budget: 62_000_000_000,
    state: "Jigawa",
    lga: "Dutse",
    sector: "AGRICULTURE",
    status: "ONGOING",
    progress: 56,
    imageUrl: "/projects/solar.png",
    ministry: "Federal Ministry of Agriculture",
    startDate: "2023-11-15",
    contractor: "Hadejia-Jam'are River Basin Auth",
    beneficiaries: 2_600_000,
  },
  {
    id: "19",
    title: "Kaduna-Kano Standard Gauge Rail Expansion",
    slug: "kaduna-kano-standard-gauge-rail",
    description:
      "203km double-track passenger and freight railway linking northern industrial hubs with speed capability up to 160km/h.",
    budget: 350_000_000_000,
    state: "Kaduna",
    lga: "Kaduna South",
    sector: "TRANSPORTATION",
    status: "ONGOING",
    progress: 64,
    imageUrl: "/projects/railway.png",
    ministry: "Federal Ministry of Transportation",
    startDate: "2023-04-15",
    contractor: "CCECC Nigeria Ltd",
    beneficiaries: 12_000_000,
  },
  {
    id: "20",
    title: "Renewed Hope Primary Health Centres Upgrade",
    slug: "renewed-hope-primary-health-kano",
    description:
      "Upgrade of 774 primary healthcare centres with solar power, modern maternity suites, and telemedicine connectivity.",
    budget: 890_000_000_000,
    state: "Kano",
    lga: "Nassarawa",
    sector: "HEALTHCARE",
    status: "ONGOING",
    progress: 62,
    imageUrl: "/projects/hospital.png",
    ministry: "Federal Ministry of Health",
    startDate: "2023-09-01",
    contractor: "Multiple Healthcare Contractors",
    beneficiaries: 45_000_000,
  },
  {
    id: "21",
    title: "Katsina Wind Farm Substation Integration",
    slug: "katsina-wind-farm-substation",
    description:
      "10MW pioneer wind farm grid integration and regional distribution sub-station supplying green power to northern Katsina.",
    budget: 40_000_000_000,
    state: "Katsina",
    lga: "Rimi",
    sector: "POWER",
    status: "ONGOING",
    progress: 53,
    imageUrl: "https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&q=80",
    ministry: "Federal Ministry of Power",
    startDate: "2024-01-01",
    contractor: "Vergne Renewable Energy",
    beneficiaries: 3_800_000,
  },
  {
    id: "22",
    title: "National Agricultural Growth Scheme - Kebbi Hub",
    slug: "national-agricultural-growth-kebbi",
    description:
      "Anchor borrowers input distribution, fertilizer subsidy delivery, and high-yield seed propagation for 500,000 rice farmers.",
    budget: 560_000_000_000,
    state: "Kebbi",
    lga: "Argungu",
    sector: "AGRICULTURE",
    status: "ONGOING",
    progress: 51,
    imageUrl: "/projects/agriculture.png",
    ministry: "Federal Ministry of Agriculture",
    startDate: "2023-07-01",
    contractor: "Agro Consortium Nigeria",
    beneficiaries: 12_000_000,
  },
  {
    id: "23",
    title: "Lokoja-Abuja Dual Carriageway Reconstruction",
    slug: "lokoja-abuja-dual-carriageway",
    description:
      "Complete rigid concrete pavement reconstruction of critical federal highway connecting North-Central to Southern Nigeria.",
    budget: 115_000_000_000,
    state: "Kogi",
    lga: "Lokoja",
    sector: "INFRASTRUCTURE",
    status: "ONGOING",
    progress: 59,
    imageUrl: "/projects/highway.png",
    ministry: "Federal Ministry of Works",
    startDate: "2023-09-15",
    contractor: "Dangote Industries Construction",
    beneficiaries: 8_500_000,
  },
  {
    id: "24",
    title: "Ilorin Agro-Processing Zone & Innovation Hub",
    slug: "ilorin-agro-processing-zone",
    description:
      "Special Agro-Industrial Processing Zone (SAPZ) featuring cold chain storage, cashew processing, and tech-driven farm logistics.",
    budget: 50_000_000_000,
    state: "Kwara",
    lga: "Ilorin South",
    sector: "AGRICULTURE",
    status: "ONGOING",
    progress: 65,
    imageUrl: "/projects/agriculture.png",
    ministry: "Federal Ministry of Agriculture",
    startDate: "2023-11-20",
    contractor: "African Development Bank Consortium",
    beneficiaries: 2_700_000,
  },
  {
    id: "25",
    title: "Lagos-Calabar Coastal Highway (Section 1)",
    slug: "lagos-calabar-coastal-highway",
    description:
      "700km 10-lane concrete coastal highway connecting Victoria Island, Lagos through Ogun, Ondo, Delta, Bayelsa to Calabar.",
    budget: 15_000_000_000_000,
    state: "Lagos",
    lga: "Eti-Osa",
    sector: "INFRASTRUCTURE",
    status: "ONGOING",
    progress: 82,
    imageUrl: "/projects/highway.png",
    ministry: "Federal Ministry of Works",
    startDate: "2024-03-15",
    contractor: "Hitech Construction Ltd",
    beneficiaries: 25_000_000,
  },
  {
    id: "26",
    title: "Lafia Lithium Processing & Industrial Corridor",
    slug: "lafia-lithium-processing-plant",
    description:
      "First commercial-scale lithium battery material processing factory, road link, and clean energy industrial park.",
    budget: 88_000_000_000,
    state: "Nasarawa",
    lga: "Lafia",
    sector: "INFRASTRUCTURE",
    status: "ONGOING",
    progress: 60,
    imageUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80",
    ministry: "Federal Ministry of Solid Minerals",
    startDate: "2023-12-10",
    contractor: "Canmax Technologies Ltd",
    beneficiaries: 1_700_000,
  },
  {
    id: "27",
    title: "Zungeru Hydroelectric Power Station Integration",
    slug: "zungeru-hydroelectric-power-station",
    description:
      "700MW hydroelectric dam commissioning and 330kV high-voltage transmission lines injection into the National Grid.",
    budget: 1_300_000_000_000,
    state: "Niger",
    lga: "Wushishi",
    sector: "POWER",
    status: "ONGOING",
    progress: 57,
    imageUrl: "/projects/water_dam.png",
    ministry: "Federal Ministry of Power",
    startDate: "2023-05-01",
    contractor: "CNEEC-SINOHYDRO Consortium",
    beneficiaries: 50_000_000,
  },
  {
    id: "28",
    title: "Renewed Hope Housing Estate - Sagamu Corridor",
    slug: "renewed-hope-housing-estate",
    description:
      "Construction of 2,500 affordable residential units with solar lighting, reticulated water, and community recreation facilities.",
    budget: 1_200_000_000_000,
    state: "Ogun",
    lga: "Sagamu",
    sector: "HOUSING",
    status: "ONGOING",
    progress: 73,
    imageUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
    ministry: "Federal Ministry of Housing",
    startDate: "2024-01-15",
    contractor: "FMBN Development Partners",
    beneficiaries: 400_000,
  },
  {
    id: "29",
    title: "Araromi-Akure Coastal Road Infrastructure",
    slug: "araromi-akure-coastal-road",
    description:
      "Dualisation of 50km coastal access highway linking Ondo oil-producing communities to Akure airport and commercial zones.",
    budget: 92_000_000_000,
    state: "Ondo",
    lga: "Ilaje",
    sector: "INFRASTRUCTURE",
    status: "ONGOING",
    progress: 64,
    imageUrl: "/projects/highway.png",
    ministry: "Federal Ministry of Works",
    startDate: "2023-11-05",
    contractor: "RCC Nigeria Ltd",
    beneficiaries: 3_100_000,
  },
  {
    id: "30",
    title: "Osogbo Transmission Substation Upgrade",
    slug: "osogbo-transmission-substation-upgrade",
    description:
      "Capacity expansion of national power dispatch center at Osogbo with digital SCADA automation systems.",
    budget: 46_000_000_000,
    state: "Osun",
    lga: "Osogbo",
    sector: "POWER",
    status: "ONGOING",
    progress: 68,
    imageUrl: "/projects/solar.png",
    ministry: "Federal Ministry of Power",
    startDate: "2023-08-10",
    contractor: "Siemens Energy Nigeria",
    beneficiaries: 4_500_000,
  },
  {
    id: "31",
    title: "Ibadan-Ilorin Standard Gauge Railway Stations",
    slug: "ibadan-ilorin-railway-stations",
    description:
      "Modern passenger terminals, freight logistics yards, and double-track rail infrastructure connecting Oyo to Kwara.",
    budget: 280_000_000_000,
    state: "Oyo",
    lga: "Ibadan North-West",
    sector: "TRANSPORTATION",
    status: "ONGOING",
    progress: 71,
    imageUrl: "/projects/railway.png",
    ministry: "Federal Ministry of Transportation",
    startDate: "2023-06-15",
    contractor: "CCECC Nigeria Ltd",
    beneficiaries: 7_800_000,
  },
  {
    id: "32",
    title: "Jos Potato Processing & Cold Storage Facilities",
    slug: "jos-potato-processing-hub",
    description:
      "Commercial climate-controlled storage hub, automated washing line, and export packaging facility for potato farmers.",
    budget: 36_000_000_000,
    state: "Plateau",
    lga: "Jos South",
    sector: "AGRICULTURE",
    status: "ONGOING",
    progress: 62,
    imageUrl: "/projects/agriculture.png",
    ministry: "Federal Ministry of Agriculture",
    startDate: "2023-10-20",
    contractor: "GIZ Agriculture Partnership",
    beneficiaries: 2_300_000,
  },
  {
    id: "33",
    title: "TraderMoni Micro-Credit Expansion & Bonny Port Link",
    slug: "tradermoni-expansion-rivers",
    description:
      "Micro-credit empowerment for 350,000 market women alongside deep seaport rail/road feeder connections.",
    budget: 180_000_000_000,
    state: "Rivers",
    lga: "Port Harcourt",
    sector: "SOCIAL_INVESTMENT",
    status: "ONGOING",
    progress: 76,
    imageUrl: "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?w=800&q=80",
    ministry: "Federal Ministry of Humanitarian Affairs",
    startDate: "2023-03-01",
    contractor: "Bank of Industry Partners",
    beneficiaries: 3_600_000,
  },
  {
    id: "34",
    title: "Great Green Wall Reforestation & Sokoto Water Works",
    slug: "great-green-wall-sokoto",
    description:
      "Shelterbelt tree planting across 200km desert frontier paired with Goronyo dam water pipeline rehabilitation.",
    budget: 280_000_000_000,
    state: "Sokoto",
    lga: "Goronyo",
    sector: "ENVIRONMENT",
    status: "ONGOING",
    progress: 50,
    imageUrl: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80",
    ministry: "Federal Ministry of Environment",
    startDate: "2023-05-01",
    contractor: "National Great Green Wall Agency",
    beneficiaries: 3_700_000,
  },
  {
    id: "35",
    title: "Mambilla Hydroelectric Power Project",
    slug: "mambilla-hydroelectric-power-project",
    description:
      "3,050 MW flagship hydroelectric dam on Dongo River providing clean power and regional flood control.",
    budget: 5_800_000_000_000,
    state: "Taraba",
    lga: "Gashaka",
    sector: "POWER",
    status: "PLANNED",
    progress: 48,
    imageUrl: "/projects/water_dam.png",
    ministry: "Federal Ministry of Power",
    startDate: "2025-01-01",
    contractor: "CGC-CGN Joint Venture",
    beneficiaries: 80_000_000,
  },
  {
    id: "36",
    title: "Damaturu Desert Barrier & Groundwater Project",
    slug: "damaturu-groundwater-project",
    description:
      "High-yield solar deep borehole network and dune stabilization shelterbelts along critical agrarian communities.",
    budget: 64_000_000_000,
    state: "Yobe",
    lga: "Damaturu",
    sector: "WATER",
    status: "ONGOING",
    progress: 46,
    imageUrl: "/projects/water_dam.png",
    ministry: "Federal Ministry of Water Resources",
    startDate: "2023-11-10",
    contractor: "Chad Basin Development Authority",
    beneficiaries: 2_100_000,
  },
  {
    id: "37",
    title: "Gusau Water Dam Expansion & Rural Surveillance Hub",
    slug: "gusau-water-dam-expansion",
    description:
      "Dredging of Gusau water reservoir, modern filtration plant installation, and rural security solar surveillance towers.",
    budget: 58_000_000_000,
    state: "Zamfara",
    lga: "Gusau",
    sector: "WATER",
    status: "ONGOING",
    progress: 44,
    imageUrl: "/projects/water_dam.png",
    ministry: "Federal Ministry of Water Resources",
    startDate: "2023-12-05",
    contractor: "Zamfara Water Resources Board",
    beneficiaries: 1_900_000,
  },
];

export function getProjectBySlug(slug: string): ProjectCard | undefined {
  return MOCK_PROJECTS.find((p) => p.slug === slug);
}

export function getProjectsBySector(sector: string): ProjectCard[] {
  return MOCK_PROJECTS.filter(
    (p) => p.sector.toLowerCase().replace(/_/g, "-") === sector.toLowerCase()
  );
}

export function getProjectsByState(state: string): ProjectCard[] {
  return MOCK_PROJECTS.filter(
    (p) => p.state.toLowerCase() === state.toLowerCase()
  );
}
