import { PrismaClient, UserRole, Sector, ProjectStatus, FeedbackType, MediaType } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding database...");

  // ─── Users ─────────────────────────────────────────────────────────────────
  const adminPassword = await bcrypt.hash("admin123", 10);
  const editorPassword = await bcrypt.hash("editor123", 10);
  const reviewerPassword = await bcrypt.hash("reviewer123", 10);
  const officerPassword = await bcrypt.hash("officer123", 10);
  const userPassword = await bcrypt.hash("user123", 10);

  const admin = await prisma.user.upsert({
    where: { email: "admin@ptla.gov.ng" },
    update: {},
    create: {
      email: "admin@ptla.gov.ng",
      name: "Super Admin",
      password: adminPassword,
      role: UserRole.SUPER_ADMIN,
    },
  });

  const editor = await prisma.user.upsert({
    where: { email: "editor@ptla.gov.ng" },
    update: {},
    create: {
      email: "editor@ptla.gov.ng",
      name: "Content Editor",
      password: editorPassword,
      role: UserRole.EDITOR,
    },
  });

  await prisma.user.upsert({
    where: { email: "reviewer@ptla.gov.ng" },
    update: {},
    create: {
      email: "reviewer@ptla.gov.ng",
      name: "Project Reviewer",
      password: reviewerPassword,
      role: UserRole.REVIEWER,
    },
  });

  await prisma.user.upsert({
    where: { email: "officer@fmwr.gov.ng" },
    update: {},
    create: {
      email: "officer@fmwr.gov.ng",
      name: "Ministry Officer",
      password: officerPassword,
      role: UserRole.MINISTRY_OFFICER,
      ministry: "Federal Ministry of Works & Housing",
    },
  });

  const publicUser = await prisma.user.upsert({
    where: { email: "user@example.com" },
    update: {},
    create: {
      email: "user@example.com",
      name: "Chukwuemeka Obi",
      password: userPassword,
      role: UserRole.PUBLIC_USER,
    },
  });

  console.log("✅ Users seeded");

  // ─── Projects (All 36 States + FCT) ─────────────────────────────────────────
  const projectsData = [
    {
      title: "Aba-Ikot Ekpene Expressway Dualisation",
      slug: "aba-ikot-ekpene-highway",
      description: "Full reconstruction and dualisation of the 34km economic arterial highway connecting commercial hub Aba to Akwa Ibom state.",
      budget: 65_000_000_000,
      fundingSource: "Federal Government of Nigeria / Sukuk Bond",
      ministry: "Federal Ministry of Works",
      state: "Abia",
      lga: "Aba North",
      latitude: 5.1216,
      longitude: 7.3733,
      startDate: new Date("2023-10-15"),
      status: ProjectStatus.ONGOING,
      progress: 68,
      sector: Sector.INFRASTRUCTURE,
      contractor: "China Civil Engineering Construction",
      beneficiaries: 3_500_000,
      heroImage: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&q=80",
    },
    {
      title: "Modibbo Adama Medical Centre Expansion",
      slug: "modibbo-adama-medical-centre",
      description: "State-of-the-art expansion of teaching hospital facilities including emergency trauma centre, diagnostic labs, and pediatric wards.",
      budget: 42_000_000_000,
      fundingSource: "Federal Government / World Bank Health Sector Fund",
      ministry: "Federal Ministry of Health",
      state: "Adamawa",
      lga: "Yola North",
      latitude: 9.2094,
      longitude: 12.4818,
      startDate: new Date("2023-11-01"),
      status: ProjectStatus.ONGOING,
      progress: 55,
      sector: Sector.HEALTHCARE,
      contractor: "Julius Berger Nigeria Plc",
      beneficiaries: 2_200_000,
      heroImage: "https://images.unsplash.com/photo-1584515901367-f1348883c27e?w=1200&q=80",
    },
    {
      title: "Ibom Deep Seaport Access Highway Corridor",
      slug: "ibom-deep-seaport-access-highway",
      description: "Dual-carriageway access corridor connecting maritime logistics networks to the Ibom Industrial City and Gulf of Guinea.",
      budget: 180_000_000_000,
      fundingSource: "Federal Government of Nigeria / AfDB",
      ministry: "Federal Ministry of Works",
      state: "Akwa Ibom",
      lga: "Ibeno",
      latitude: 4.5422,
      longitude: 7.9861,
      startDate: new Date("2024-01-10"),
      status: ProjectStatus.ONGOING,
      progress: 72,
      sector: Sector.INFRASTRUCTURE,
      contractor: "Hitech Construction Ltd",
      beneficiaries: 5_400_000,
      heroImage: "https://images.unsplash.com/photo-1618828665011-0abd9e3f478d?w=1200&q=80",
    },
    {
      title: "Second Niger Bridge Phase II Access Roads",
      slug: "second-niger-bridge-phase-ii",
      description: "Completion of Phase II connecting interchanges from Asaba through Onitsha to the Ihiala commercial corridor.",
      budget: 95_000_000_000,
      fundingSource: "Federal Infrastructure Development Fund",
      ministry: "Federal Ministry of Works",
      state: "Anambra",
      lga: "Onitsha South",
      latitude: 6.1360,
      longitude: 6.7580,
      startDate: new Date("2023-08-01"),
      status: ProjectStatus.ONGOING,
      progress: 75,
      sector: Sector.TRANSPORTATION,
      contractor: "Julius Berger Nigeria Plc",
      beneficiaries: 6_000_000,
      heroImage: "https://images.unsplash.com/photo-1515162305285-0293e4767cc2?w=1200&q=80",
    },
    {
      title: "Northeast Regional Solar Substation Grid",
      slug: "northeast-regional-solar-grid",
      description: "150MW utility-scale solar photovoltaic plant with smart distribution grid integrating clean energy across Bauchi and neighbors.",
      budget: 78_000_000_000,
      fundingSource: "Federal Government / Rural Electrification Agency",
      ministry: "Federal Ministry of Power",
      state: "Bauchi",
      lga: "Ganjuwa",
      latitude: 10.4500,
      longitude: 9.8000,
      startDate: new Date("2024-02-15"),
      status: ProjectStatus.ONGOING,
      progress: 52,
      sector: Sector.POWER,
      contractor: "Sterling & Wilson Renewable Power",
      beneficiaries: 4_100_000,
      heroImage: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200&q=80",
    },
    {
      title: "Nembe-Brass Coastal Road & Wetland Preservation",
      slug: "nembe-brass-coastal-road",
      description: "Strategic coastal road unlocking Brass Island crude terminal and logistics base, alongside marine wetland ecosystem protection.",
      budget: 110_000_000_000,
      fundingSource: "Federal Government of Nigeria / NDDC",
      ministry: "Federal Ministry of Environment",
      state: "Bayelsa",
      lga: "Brass",
      latitude: 4.3167,
      longitude: 6.2333,
      startDate: new Date("2023-09-20"),
      status: ProjectStatus.ONGOING,
      progress: 61,
      sector: Sector.ENVIRONMENT,
      contractor: "Setraco Nigeria Ltd",
      beneficiaries: 1_800_000,
      heroImage: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=1200&q=80",
    },
    {
      title: "Makurdi Grain Storage Silos & Agro Logistics Hub",
      slug: "makurdi-grain-silos-hub",
      description: "100,000-tonne strategic grain reserves facility with automated drying and processing infrastructure to enhance national food security.",
      budget: 48_000_000_000,
      fundingSource: "Federal Ministry of Agriculture & Food Security",
      ministry: "Federal Ministry of Agriculture",
      state: "Benue",
      lga: "Makurdi",
      latitude: 7.7333,
      longitude: 8.5333,
      startDate: new Date("2023-07-15"),
      status: ProjectStatus.ONGOING,
      progress: 58,
      sector: Sector.AGRICULTURE,
      contractor: "Agro Allied Industries Ltd",
      beneficiaries: 3_200_000,
      heroImage: "https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?w=1200&q=80",
    },
    {
      title: "Maiduguri Clean Water Initiative",
      slug: "maiduguri-clean-water-initiative",
      description: "Comprehensive municipal water treatment plant restoration, borehole networks, and distribution piping serving resilient communities.",
      budget: 120_000_000_000,
      fundingSource: "Federal Government / European Union Water Grant",
      ministry: "Federal Ministry of Water Resources",
      state: "Borno",
      lga: "Maiduguri",
      latitude: 11.8311,
      longitude: 13.1510,
      startDate: new Date("2023-11-01"),
      status: ProjectStatus.ONGOING,
      progress: 45,
      sector: Sector.WATER,
      contractor: "China Harbour Engineering",
      beneficiaries: 2_800_000,
      heroImage: "https://images.unsplash.com/photo-1541905082-d7340b07b36f?w=1200&q=80",
    },
    {
      title: "Calabar Deep Sea Port Access & Tourism Corridor",
      slug: "calabar-deep-sea-port-corridor",
      description: "Channel dredging and dualized coastal expressway boost connecting Calabar Seaport to the Tinapa Eco-Tourism Free Zone.",
      budget: 140_000_000_000,
      fundingSource: "Federal Ministry of Transportation / NPA",
      ministry: "Federal Ministry of Transportation",
      state: "Cross River",
      lga: "Calabar South",
      latitude: 4.9587,
      longitude: 8.3269,
      startDate: new Date("2024-03-01"),
      status: ProjectStatus.ONGOING,
      progress: 63,
      sector: Sector.TRANSPORTATION,
      contractor: "Dredging International NV",
      beneficiaries: 2_900_000,
      heroImage: "https://images.unsplash.com/photo-1515162305285-0293e4767cc2?w=1200&q=80",
    },
    {
      title: "Warri-Itakpe Rail Commercial Extension",
      slug: "warri-itakpe-rail-extension",
      description: "Modernization and spur line extension connecting Warri Port to industrial gas processing plants in Kwale.",
      budget: 210_000_000_000,
      fundingSource: "Federal Government / Nigerian Railway Corporation",
      ministry: "Federal Ministry of Transportation",
      state: "Delta",
      lga: "Warri South",
      latitude: 5.5167,
      longitude: 5.7500,
      startDate: new Date("2023-05-10"),
      status: ProjectStatus.ONGOING,
      progress: 70,
      sector: Sector.TRANSPORTATION,
      contractor: "CCECC Nigeria Ltd",
      beneficiaries: 4_800_000,
      heroImage: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=1200&q=80",
    },
    {
      title: "Abakaliki Rice Processing & Irrigation Scheme",
      slug: "abakaliki-rice-irrigation-scheme",
      description: "5,000-hectare automated rice irrigation dam and commercial milling hub boosting local production and export readiness.",
      budget: 38_000_000_000,
      fundingSource: "Federal Government / IFAD Value Chain Development",
      ministry: "Federal Ministry of Agriculture",
      state: "Ebonyi",
      lga: "Abakaliki",
      latitude: 6.3250,
      longitude: 8.1139,
      startDate: new Date("2023-08-20"),
      status: ProjectStatus.ONGOING,
      progress: 66,
      sector: Sector.AGRICULTURE,
      contractor: "OLAM Rice Farm Partners",
      beneficiaries: 1_900_000,
      heroImage: "https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?w=1200&q=80",
    },
    {
      title: "Benin Digital Innovation Park & Fiber Backbone",
      slug: "benin-digital-innovation-park",
      description: "3,000-seat technology incubator, software development park, and regional high-speed optic fiber transmission backbone.",
      budget: 55_000_000_000,
      fundingSource: "Federal Ministry of Communications, Innovation & Digital Economy",
      ministry: "Federal Ministry of Communications",
      state: "Edo",
      lga: "Oredo",
      latitude: 6.3333,
      longitude: 5.6222,
      startDate: new Date("2023-09-01"),
      status: ProjectStatus.ONGOING,
      progress: 71,
      sector: Sector.TECHNOLOGY,
      contractor: "MainOne Cable Company",
      beneficiaries: 3_100_000,
      heroImage: "https://images.unsplash.com/photo-1573164713988-8665fc963095?w=1200&q=80",
    },
    {
      title: "Ado-Ekiti Knowledge Zone Power Substation",
      slug: "ado-ekiti-knowledge-zone-power",
      description: "Dedicated 132/33kV power transmission substation guaranteeing 24/7 power to the Ekiti Special Agro-Industrial Processing Zone.",
      budget: 32_000_000_000,
      fundingSource: "Federal Government of Nigeria / TCN",
      ministry: "Federal Ministry of Power",
      state: "Ekiti",
      lga: "Ado Ekiti",
      latitude: 7.6211,
      longitude: 5.2214,
      startDate: new Date("2024-01-15"),
      status: ProjectStatus.ONGOING,
      progress: 69,
      sector: Sector.POWER,
      contractor: "Transmission Company of Nigeria",
      beneficiaries: 1_600_000,
      heroImage: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200&q=80",
    },
    {
      title: "Enugu Smart Education Hub & Digital Library",
      slug: "enugu-smart-education-hub",
      description: "Modern tertiary e-learning infrastructure, STEM labs, and teacher training complex serving southeastern academic institutions.",
      budget: 45_000_000_000,
      fundingSource: "Federal Ministry of Education / TETFund",
      ministry: "Federal Ministry of Education",
      state: "Enugu",
      lga: "Enugu North",
      latitude: 6.4402,
      longitude: 7.4943,
      startDate: new Date("2023-07-01"),
      status: ProjectStatus.ONGOING,
      progress: 74,
      sector: Sector.EDUCATION,
      contractor: "TetFund Construction Partners",
      beneficiaries: 2_400_000,
      heroImage: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=1200&q=80",
    },
    {
      title: "National Digital Identity Programme",
      slug: "national-digital-identity-programme",
      description: "Nationwide rollout of digital identity infrastructure enabling seamless access to government services and financial inclusion.",
      budget: 450_000_000_000,
      fundingSource: "Federal Government of Nigeria",
      ministry: "Federal Ministry of Communications",
      state: "FCT",
      lga: "Abuja Municipal",
      latitude: 9.0765,
      longitude: 7.3986,
      startDate: new Date("2023-06-01"),
      status: ProjectStatus.ONGOING,
      progress: 78,
      sector: Sector.TECHNOLOGY,
      contractor: "NIMC Consortium",
      beneficiaries: 120_000_000,
      heroImage: "https://images.unsplash.com/photo-1573164713988-8665fc963095?w=1200&q=80",
    },
    {
      title: "Dadin Kowa Multipurpose Hydro & Irrigation",
      slug: "dadin-kowa-hydro-irrigation",
      description: "40MW hydro-power plant expansion coupled with a 6,000-hectare gravity irrigation network for dry season farming.",
      budget: 85_000_000_000,
      fundingSource: "Federal Ministry of Water Resources / Upper Benue RBDA",
      ministry: "Federal Ministry of Water Resources",
      state: "Gombe",
      lga: "Yamaltu/Deba",
      latitude: 10.3000,
      longitude: 11.5000,
      startDate: new Date("2023-12-01"),
      status: ProjectStatus.ONGOING,
      progress: 54,
      sector: Sector.WATER,
      contractor: "Mabon Limited",
      beneficiaries: 2_100_000,
      heroImage: "https://images.unsplash.com/photo-1541905082-d7340b07b36f?w=1200&q=80",
    },
    {
      title: "Owerri-Port Harcourt Dual Expressway Rehabilitation",
      slug: "owerri-port-harcourt-highway",
      description: "Heavy-duty asphalt pavement reconstruction and flyover interchange installation linking Imo commercial trade to Rivers oil terminals.",
      budget: 72_000_000_000,
      fundingSource: "Federal Ministry of Works / Highway Maintenance Fund",
      ministry: "Federal Ministry of Works",
      state: "Imo",
      lga: "Owerri Municipal",
      latitude: 5.4833,
      longitude: 7.0333,
      startDate: new Date("2023-10-01"),
      status: ProjectStatus.ONGOING,
      progress: 67,
      sector: Sector.INFRASTRUCTURE,
      contractor: "Craneburg Construction",
      beneficiaries: 4_200_000,
      heroImage: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&q=80",
    },
    {
      title: "Dutse Solar Power Grid & Wheat Scheme",
      slug: "dutse-solar-wheat-scheme",
      description: "100MW off-grid solar installation powering 15,000 hectares of mechanized wheat farms along the Hadejia river valley.",
      budget: 62_000_000_000,
      fundingSource: "Federal Government / National Agricultural Development Fund",
      ministry: "Federal Ministry of Agriculture",
      state: "Jigawa",
      lga: "Dutse",
      latitude: 11.7000,
      longitude: 9.3333,
      startDate: new Date("2023-11-15"),
      status: ProjectStatus.ONGOING,
      progress: 56,
      sector: Sector.AGRICULTURE,
      contractor: "Hadejia-Jam'are River Basin Auth",
      beneficiaries: 2_600_000,
      heroImage: "https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?w=1200&q=80",
    },
    {
      title: "Kaduna-Kano Standard Gauge Rail Expansion",
      slug: "kaduna-kano-standard-gauge-rail",
      description: "203km double-track passenger and freight railway linking northern industrial hubs with speed capability up to 160km/h.",
      budget: 350_000_000_000,
      fundingSource: "Federal Government / China Exim Bank",
      ministry: "Federal Ministry of Transportation",
      state: "Kaduna",
      lga: "Kaduna South",
      latitude: 10.5167,
      longitude: 7.4333,
      startDate: new Date("2023-04-15"),
      status: ProjectStatus.ONGOING,
      progress: 64,
      sector: Sector.TRANSPORTATION,
      contractor: "CCECC Nigeria Ltd",
      beneficiaries: 12_000_000,
      heroImage: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=1200&q=80",
    },
    {
      title: "Renewed Hope Primary Health Centres Upgrade",
      slug: "renewed-hope-primary-health-kano",
      description: "Upgrade of 774 primary healthcare centres with solar power, modern maternity suites, and telemedicine connectivity.",
      budget: 890_000_000_000,
      fundingSource: "Federal Ministry of Health / World Bank",
      ministry: "Federal Ministry of Health",
      state: "Kano",
      lga: "Nassarawa",
      latitude: 11.9964,
      longitude: 8.5166,
      startDate: new Date("2023-09-01"),
      status: ProjectStatus.ONGOING,
      progress: 62,
      sector: Sector.HEALTHCARE,
      contractor: "Multiple Healthcare Contractors",
      beneficiaries: 45_000_000,
      heroImage: "https://images.unsplash.com/photo-1584515901367-f1348883c27e?w=1200&q=80",
    },
    {
      title: "Katsina Wind Farm Substation Integration",
      slug: "katsina-wind-farm-substation",
      description: "10MW pioneer wind farm grid integration and regional distribution sub-station supplying green power to northern Katsina.",
      budget: 40_000_000_000,
      fundingSource: "Federal Ministry of Power / REA",
      ministry: "Federal Ministry of Power",
      state: "Katsina",
      lga: "Rimi",
      latitude: 12.8500,
      longitude: 7.7000,
      startDate: new Date("2024-01-01"),
      status: ProjectStatus.ONGOING,
      progress: 53,
      sector: Sector.POWER,
      contractor: "Vergne Renewable Energy",
      beneficiaries: 3_800_000,
      heroImage: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200&q=80",
    },
    {
      title: "National Agricultural Growth Scheme - Kebbi Hub",
      slug: "national-agricultural-growth-kebbi",
      description: "Anchor borrowers input distribution, fertilizer subsidy delivery, and high-yield seed propagation for 500,000 rice farmers.",
      budget: 560_000_000_000,
      fundingSource: "Federal Government / AfDB",
      ministry: "Federal Ministry of Agriculture",
      state: "Kebbi",
      lga: "Argungu",
      latitude: 12.7499,
      longitude: 4.5228,
      startDate: new Date("2023-07-01"),
      status: ProjectStatus.ONGOING,
      progress: 51,
      sector: Sector.AGRICULTURE,
      contractor: "Agro Consortium Nigeria",
      beneficiaries: 12_000_000,
      heroImage: "https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?w=1200&q=80",
    },
    {
      title: "Lokoja-Abuja Dual Carriageway Reconstruction",
      slug: "lokoja-abuja-dual-carriageway",
      description: "Complete rigid concrete pavement reconstruction of critical federal highway connecting North-Central to Southern Nigeria.",
      budget: 115_000_000_000,
      fundingSource: "Federal Ministry of Works / Tax Credit Scheme",
      ministry: "Federal Ministry of Works",
      state: "Kogi",
      lga: "Lokoja",
      latitude: 7.8024,
      longitude: 6.7430,
      startDate: new Date("2023-09-15"),
      status: ProjectStatus.ONGOING,
      progress: 59,
      sector: Sector.INFRASTRUCTURE,
      contractor: "Dangote Industries Construction",
      beneficiaries: 8_500_000,
      heroImage: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&q=80",
    },
    {
      title: "Ilorin Agro-Processing Zone & Innovation Hub",
      slug: "ilorin-agro-processing-zone",
      description: "Special Agro-Industrial Processing Zone (SAPZ) featuring cold chain storage, cashew processing, and tech-driven farm logistics.",
      budget: 50_000_000_000,
      fundingSource: "Federal Ministry of Agriculture / AfDB",
      ministry: "Federal Ministry of Agriculture",
      state: "Kwara",
      lga: "Ilorin South",
      latitude: 8.4799,
      longitude: 4.5418,
      startDate: new Date("2023-11-20"),
      status: ProjectStatus.ONGOING,
      progress: 65,
      sector: Sector.AGRICULTURE,
      contractor: "African Development Bank Consortium",
      beneficiaries: 2_700_000,
      heroImage: "https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?w=1200&q=80",
    },
    {
      title: "Lagos-Calabar Coastal Highway (Section 1)",
      slug: "lagos-calabar-coastal-highway",
      description: "700km 10-lane concrete coastal highway connecting Victoria Island, Lagos through Ogun, Ondo, Delta, Bayelsa to Calabar.",
      budget: 15_000_000_000_000,
      fundingSource: "Federal Government of Nigeria / EPC+F Model",
      ministry: "Federal Ministry of Works",
      state: "Lagos",
      lga: "Eti-Osa",
      latitude: 6.4281,
      longitude: 3.4219,
      startDate: new Date("2024-03-15"),
      status: ProjectStatus.ONGOING,
      progress: 82,
      sector: Sector.INFRASTRUCTURE,
      contractor: "Hitech Construction Ltd",
      beneficiaries: 25_000_000,
      heroImage: "https://images.unsplash.com/photo-1618828665011-0abd9e3f478d?w=1200&q=80",
    },
    {
      title: "Lafia Lithium Processing & Industrial Corridor",
      slug: "lafia-lithium-processing-plant",
      description: "First commercial-scale lithium battery material processing factory, road link, and clean energy industrial park.",
      budget: 88_000_000_000,
      fundingSource: "Federal Ministry of Solid Minerals Development",
      ministry: "Federal Ministry of Solid Minerals",
      state: "Nasarawa",
      lga: "Lafia",
      latitude: 8.4933,
      longitude: 8.5153,
      startDate: new Date("2023-12-10"),
      status: ProjectStatus.ONGOING,
      progress: 60,
      sector: Sector.INFRASTRUCTURE,
      contractor: "Canmax Technologies Ltd",
      beneficiaries: 1_700_000,
      heroImage: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&q=80",
    },
    {
      title: "Zungeru Hydroelectric Power Station Integration",
      slug: "zungeru-hydroelectric-power-station",
      description: "700MW hydroelectric dam commissioning and 330kV high-voltage transmission lines injection into the National Grid.",
      budget: 1_300_000_000_000,
      fundingSource: "Federal Ministry of Power / Exim Bank",
      ministry: "Federal Ministry of Power",
      state: "Niger",
      lga: "Wushishi",
      latitude: 9.8000,
      longitude: 6.1500,
      startDate: new Date("2023-05-01"),
      status: ProjectStatus.ONGOING,
      progress: 57,
      sector: Sector.POWER,
      contractor: "CNEEC-SINOHYDRO Consortium",
      beneficiaries: 50_000_000,
      heroImage: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200&q=80",
    },
    {
      title: "Renewed Hope Housing Estate - Sagamu Corridor",
      slug: "renewed-hope-housing-estate",
      description: "Construction of 2,500 affordable residential units with solar lighting, reticulated water, and community recreation facilities.",
      budget: 1_200_000_000_000,
      fundingSource: "Federal Ministry of Housing / FMBN",
      ministry: "Federal Ministry of Housing",
      state: "Ogun",
      lga: "Sagamu",
      latitude: 6.8483,
      longitude: 3.6467,
      startDate: new Date("2024-01-15"),
      status: ProjectStatus.ONGOING,
      progress: 73,
      sector: Sector.HOUSING,
      contractor: "FMBN Development Partners",
      beneficiaries: 400_000,
      heroImage: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    },
    {
      title: "Araromi-Akure Coastal Road Infrastructure",
      slug: "araromi-akure-coastal-road",
      description: "Dualisation of 50km coastal access highway linking Ondo oil-producing communities to Akure airport and commercial zones.",
      budget: 92_000_000_000,
      fundingSource: "Federal Ministry of Works / OSOPADEC Support Fund",
      ministry: "Federal Ministry of Works",
      state: "Ondo",
      lga: "Ilaje",
      latitude: 6.0000,
      longitude: 4.8000,
      startDate: new Date("2023-11-05"),
      status: ProjectStatus.ONGOING,
      progress: 64,
      sector: Sector.INFRASTRUCTURE,
      contractor: "RCC Nigeria Ltd",
      beneficiaries: 3_100_000,
      heroImage: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&q=80",
    },
    {
      title: "Osogbo Transmission Substation Upgrade",
      slug: "osogbo-transmission-substation-upgrade",
      description: "Capacity expansion of national power dispatch center at Osogbo with digital SCADA automation systems.",
      budget: 46_000_000_000,
      fundingSource: "Federal Ministry of Power / Siemens PPI",
      ministry: "Federal Ministry of Power",
      state: "Osun",
      lga: "Osogbo",
      latitude: 7.7667,
      longitude: 4.5667,
      startDate: new Date("2023-08-10"),
      status: ProjectStatus.ONGOING,
      progress: 68,
      sector: Sector.POWER,
      contractor: "Siemens Energy Nigeria",
      beneficiaries: 4_500_000,
      heroImage: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200&q=80",
    },
    {
      title: "Ibadan-Ilorin Standard Gauge Railway Stations",
      slug: "ibadan-ilorin-railway-stations",
      description: "Modern passenger terminals, freight logistics yards, and double-track rail infrastructure connecting Oyo to Kwara.",
      budget: 280_000_000_000,
      fundingSource: "Federal Ministry of Transportation / CCECC",
      ministry: "Federal Ministry of Transportation",
      state: "Oyo",
      lga: "Ibadan North-West",
      latitude: 7.3964,
      longitude: 3.8967,
      startDate: new Date("2023-06-15"),
      status: ProjectStatus.ONGOING,
      progress: 71,
      sector: Sector.TRANSPORTATION,
      contractor: "CCECC Nigeria Ltd",
      beneficiaries: 7_800_000,
      heroImage: "https://images.unsplash.com/photo-1515162305285-0293e4767cc2?w=1200&q=80",
    },
    {
      title: "Jos Potato Processing & Cold Storage Facilities",
      slug: "jos-potato-processing-hub",
      description: "Commercial climate-controlled storage hub, automated washing line, and export packaging facility for potato farmers.",
      budget: 36_000_000_000,
      fundingSource: "Federal Ministry of Agriculture / Plateau Agro Dev",
      ministry: "Federal Ministry of Agriculture",
      state: "Plateau",
      lga: "Jos South",
      latitude: 9.8000,
      longitude: 8.8833,
      startDate: new Date("2023-10-20"),
      status: ProjectStatus.ONGOING,
      progress: 62,
      sector: Sector.AGRICULTURE,
      contractor: "GIZ Agriculture Partnership",
      beneficiaries: 2_300_000,
      heroImage: "https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?w=1200&q=80",
    },
    {
      title: "TraderMoni Micro-Credit Expansion & Bonny Port Link",
      slug: "tradermoni-expansion-rivers",
      description: "Micro-credit empowerment for 350,000 market women alongside deep seaport rail/road feeder connections.",
      budget: 180_000_000_000,
      fundingSource: "Federal Ministry of Humanitarian Affairs / NSIP",
      ministry: "Federal Ministry of Humanitarian Affairs",
      state: "Rivers",
      lga: "Port Harcourt",
      latitude: 4.8156,
      longitude: 7.0498,
      startDate: new Date("2023-03-01"),
      status: ProjectStatus.ONGOING,
      progress: 76,
      sector: Sector.SOCIAL_INVESTMENT,
      contractor: "Bank of Industry Partners",
      beneficiaries: 3_600_000,
      heroImage: "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?w=1200&q=80",
    },
    {
      title: "Great Green Wall Reforestation & Sokoto Water Works",
      slug: "great-green-wall-sokoto",
      description: "Shelterbelt tree planting across 200km desert frontier paired with Goronyo dam water pipeline rehabilitation.",
      budget: 280_000_000_000,
      fundingSource: "Federal Ministry of Environment / AU Green Wall Fund",
      ministry: "Federal Ministry of Environment",
      state: "Sokoto",
      lga: "Goronyo",
      latitude: 13.2845,
      longitude: 5.1022,
      startDate: new Date("2023-05-01"),
      status: ProjectStatus.ONGOING,
      progress: 50,
      sector: Sector.ENVIRONMENT,
      contractor: "National Great Green Wall Agency",
      beneficiaries: 3_700_000,
      heroImage: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=1200&q=80",
    },
    {
      title: "Mambilla Hydroelectric Power Project",
      slug: "mambilla-hydroelectric-power-project",
      description: "3,050 MW flagship hydroelectric dam on Dongo River providing clean power and regional flood control.",
      budget: 5_800_000_000_000,
      fundingSource: "Chinese Export-Import Bank / Federal Government",
      ministry: "Federal Ministry of Power",
      state: "Taraba",
      lga: "Gashaka",
      latitude: 7.2967,
      longitude: 11.5527,
      startDate: new Date("2025-01-01"),
      status: ProjectStatus.PLANNED,
      progress: 48,
      sector: Sector.POWER,
      contractor: "CGC-CGN Joint Venture",
      beneficiaries: 80_000_000,
      heroImage: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200&q=80",
    },
    {
      title: "Damaturu Desert Barrier & Groundwater Project",
      slug: "damaturu-groundwater-project",
      description: "High-yield solar deep borehole network and dune stabilization shelterbelts along critical agrarian communities.",
      budget: 64_000_000_000,
      fundingSource: "Federal Ministry of Water Resources / North-East Dev Commission",
      ministry: "Federal Ministry of Water Resources",
      state: "Yobe",
      lga: "Damaturu",
      latitude: 11.7470,
      longitude: 11.9660,
      startDate: new Date("2023-11-10"),
      status: ProjectStatus.ONGOING,
      progress: 46,
      sector: Sector.WATER,
      contractor: "Chad Basin Development Authority",
      beneficiaries: 2_100_000,
      heroImage: "https://images.unsplash.com/photo-1541905082-d7340b07b36f?w=1200&q=80",
    },
    {
      title: "Gusau Water Dam Expansion & Rural Surveillance Hub",
      slug: "gusau-water-dam-expansion",
      description: "Dredging of Gusau water reservoir, modern filtration plant installation, and rural security solar surveillance towers.",
      budget: 58_000_000_000,
      fundingSource: "Federal Ministry of Water Resources / Federal Ministry of Defence",
      ministry: "Federal Ministry of Water Resources",
      state: "Zamfara",
      lga: "Gusau",
      latitude: 12.1700,
      longitude: 6.6600,
      startDate: new Date("2023-12-05"),
      status: ProjectStatus.ONGOING,
      progress: 44,
      sector: Sector.WATER,
      contractor: "Zamfara Water Resources Board",
      beneficiaries: 1_900_000,
      heroImage: "https://images.unsplash.com/photo-1541905082-d7340b07b36f?w=1200&q=80",
    },
  ];

  const createdProjects: Array<{ id: string; slug: string }> = [];

  for (const data of projectsData) {
    const existing = await prisma.project.findUnique({ where: { slug: data.slug } });
    if (!existing) {
      const project = await prisma.project.create({
        data: {
          ...data,
          createdById: admin.id,
          publishedAt: new Date(),
        },
      });
      createdProjects.push({ id: project.id, slug: project.slug });
    } else {
      await prisma.project.update({
        where: { id: existing.id },
        data: { heroImage: data.heroImage, progress: data.progress, budget: data.budget },
      });
      createdProjects.push({ id: existing.id, slug: existing.slug });
    }
  }

  console.log(`✅ ${createdProjects.length} projects seeded across 37 states & FCT`);

  // ─── Timeline Entries ───────────────────────────────────────────────────────
  for (const proj of createdProjects) {
    const count = await prisma.timelineEntry.count({ where: { projectId: proj.id } });
    if (count === 0) {
      await prisma.timelineEntry.createMany({
        data: [
          { projectId: proj.id, title: "Project Initiation", description: "Presidential directive signed; budget allocated.", date: new Date("2023-06-01"), order: 1 },
          { projectId: proj.id, title: "Site Assessment", description: "Environmental and geotechnical surveys completed.", date: new Date("2023-09-15"), order: 2 },
          { projectId: proj.id, title: "Contractor Procurement", description: "Competitive tender concluded; contract awarded.", date: new Date("2024-01-10"), order: 3 },
          { projectId: proj.id, title: "Construction Phase 1", description: "Foundation and structural works commenced.", date: new Date("2024-04-01"), order: 4 },
          { projectId: proj.id, title: "Mid-term Review", description: "50% milestone inspection by Federal team.", date: new Date("2025-01-15"), order: 5 },
        ],
      });
    }
  }

  console.log("✅ Timeline entries seeded");

  // ─── Media ─────────────────────────────────────────────────────────────────
  for (const proj of createdProjects.slice(0, 10)) {
    const count = await prisma.media.count({ where: { projectId: proj.id } });
    if (count === 0) {
      await prisma.media.createMany({
        data: [
          { projectId: proj.id, type: MediaType.PHOTO, title: "Project Overview", url: "https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800&q=80", order: 1 },
          { projectId: proj.id, type: MediaType.DRONE, title: "Aerial View", url: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&q=80", caption: "Drone footage captured October 2024", order: 2 },
          { projectId: proj.id, type: MediaType.BEFORE_AFTER, title: "Before Construction", url: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=800&q=80", caption: "Site condition before project commencement", order: 3 },
        ],
      });
    }
  }

  console.log("✅ Media seeded");

  console.log("\n🎉 Seeding complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
